# Generated by Django 4.2 on 2023-05-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
